#!/usr/bin/env python3
"""
build_reel.py — Turn the media generated by generate_shots.py into a
finished video: each shot becomes a clip sized to its slot duration (stills
get a Ken-Burns pan/zoom; real video clips get blur-fill letterboxed to fit
without cropping out hands/action), crossfaded together.

Audio priority per shot:
  1. `source_audio` in shots.json, if set — muxed under the whole reel
     (e.g. a voiceover, or a track you explicitly want to reuse).
  2. Otherwise, each video shot's own native audio track (if it has one) is
     kept and crossfaded in sync with the video — e.g. generated
     carving/foley sound from grok-imagine-video. Image shots contribute
     silence for their slot.
  3. Silent, if neither applies.

See imageGenSkill.MD for the full pipeline and the shots.json format.

Usage:
    python build_reel.py --shots wolf_reel/shots.json

Output: <project>/final/<project>_<timestamp>.mp4
"""

import argparse
import datetime
import json
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.abspath(__file__))

DEFAULT_W, DEFAULT_H, DEFAULT_FPS = 1080, 1920, 30
DEFAULT_CROSSFADE = 0.3
SAMPLE_RATE = 44100

IMAGE_EXT = (".png", ".jpg", ".jpeg", ".webp")
VIDEO_EXT = (".mp4", ".mov", ".m4v", ".webm")


def _find(binary):
    local = os.path.join(ROOT, "tools", binary + ".exe")
    if os.path.exists(local):
        return local
    onpath = shutil.which(binary)
    if onpath:
        return onpath
    sys.exit(f"ERROR: could not find {binary}. Put {binary}.exe in ./tools/.")


FF = _find("ffmpeg")
FFPROBE = _find("ffprobe")


def run(args, label=""):
    r = subprocess.run([FF, "-y", *args], capture_output=True, text=True)
    if r.returncode != 0:
        print(f"\nFFmpeg failed [{label}]:\n{r.stderr[-1500:]}", file=sys.stderr)
        sys.exit(1)


def duration_of(path):
    r = subprocess.run(
        [FFPROBE, "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", path],
        capture_output=True, text=True,
    )
    try:
        return float(r.stdout.strip())
    except ValueError:
        return None


def has_audio_stream(path):
    r = subprocess.run(
        [FFPROBE, "-v", "error", "-select_streams", "a",
         "-show_entries", "stream=index",
         "-of", "default=noprint_wrappers=1:nokey=1", path],
        capture_output=True, text=True,
    )
    return bool(r.stdout.strip())


def load_config(shots_path):
    if not os.path.isfile(shots_path):
        sys.exit(f"ERROR: shots file not found: {shots_path}")
    with open(shots_path, "r", encoding="utf-8") as f:
        cfg = json.load(f)
    if "shots" not in cfg or not cfg["shots"]:
        sys.exit(f"ERROR: {shots_path} has no \"shots\" list.")
    # A shot with no "seconds" is a seed/intermediate (e.g. an image used only
    # to seed an image_to_video shot) and is excluded from the timeline.
    timeline = [s for s in cfg["shots"] if "seconds" in s]
    if not timeline:
        sys.exit(f"ERROR: no shots in {shots_path} have a \"seconds\" field, "
                  f"so there is nothing to assemble into a timeline.")
    for shot in timeline:
        if "name" not in shot:
            sys.exit(f"ERROR: each timeline shot needs a \"name\": {shot}")
    cfg["shots"] = timeline
    return cfg


def find_shot_media(media_dir, name):
    for ext in IMAGE_EXT:
        p = os.path.join(media_dir, name + ext)
        if os.path.isfile(p):
            return p, "image"
    for ext in VIDEO_EXT:
        p = os.path.join(media_dir, name + ext)
        if os.path.isfile(p):
            return p, "video"
    return None, None


def render_image_clip(img_path, seconds, w, h, fps, tmp_dir, idx):
    frames = max(1, int(round(seconds * fps)))
    vf = (
        f"scale={w*2}:{h*2}:force_original_aspect_ratio=increase,"
        f"crop={w*2}:{h*2},"
        f"zoompan=z='min(zoom+0.0006,1.12)':d={frames}:"
        f"x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':"
        f"s={w}x{h}:fps={fps},setsar=1,format=yuv420p"
    )
    dst = os.path.join(tmp_dir, f"clip_{idx:02d}.mp4")
    run(["-loop", "1", "-i", img_path, "-t", f"{seconds:.3f}", "-vf", vf,
         "-c:v", "libx264", "-pix_fmt", "yuv420p", "-r", str(fps), "-an", dst],
        os.path.basename(img_path))
    return dst


def render_video_clip(clip_path, seconds, w, h, fps, tmp_dir, idx):
    """Cover-crop to the target frame. Request `aspect_ratio` in shots.json
    (e.g. "9:16") when generating so the source clip is already close to
    vertical — this crop should then be minor, not a landscape-to-portrait
    hack. See imageGenSkill.MD."""
    dst = os.path.join(tmp_dir, f"clip_{idx:02d}.mp4")
    vf = (f"scale={w}:{h}:force_original_aspect_ratio=increase,"
          f"crop={w}:{h},setsar=1,fps={fps},format=yuv420p")
    # -stream_loop -1 covers clips shorter than the requested slot; -t always
    # trims to exactly `seconds` regardless of the source clip's own length.
    run(["-stream_loop", "-1", "-i", clip_path, "-t", f"{seconds:.3f}",
         "-vf", vf, "-c:v", "libx264", "-pix_fmt", "yuv420p", "-an", dst],
        os.path.basename(clip_path))
    return dst


def render_clip_audio(path, kind, seconds, tmp_dir, idx):
    """Return `seconds` of audio for this shot: the clip's own audio track
    (looped/trimmed to fit) if it's a video with audio, else silence."""
    dst = os.path.join(tmp_dir, f"aud_{idx:02d}.wav")
    if kind == "video" and has_audio_stream(path):
        run(["-stream_loop", "-1", "-i", path, "-t", f"{seconds:.3f}",
             "-vn", "-ac", "2", "-ar", str(SAMPLE_RATE), dst],
            f"audio {os.path.basename(path)}")
    else:
        run(["-f", "lavfi", "-i", f"anullsrc=r={SAMPLE_RATE}:cl=stereo",
             "-t", f"{seconds:.3f}", dst], "silence")
    return dst


def build_xfade_chain(n, clip_durs, crossfade):
    """Iteratively chain n video clips with crossfade transitions. Returns
    (filter_complex string or None, output label, final duration)."""
    if n == 1:
        return None, "0:v", clip_durs[0]
    filters = []
    running_dur = clip_durs[0]
    prev_label = "[0:v]"
    for i in range(1, n):
        offset = max(0.0, running_dur - crossfade)
        out_label = f"v{i}" if i < n - 1 else "vout"
        filters.append(
            f"{prev_label}[{i}:v]xfade=transition=fade:duration={crossfade:.3f}:"
            f"offset={offset:.3f}[{out_label}]"
        )
        running_dur = running_dur + clip_durs[i] - crossfade
        prev_label = f"[{out_label}]"
    return ";".join(filters), "vout", running_dur


def build_acrossfade_chain(n, crossfade):
    """Iteratively chain n audio clips with crossfade transitions (acrossfade
    handles its own timing internally — no offset needed). Returns
    (filter_complex string or None, output label)."""
    if n == 1:
        return None, "0:a"
    if crossfade <= 0:
        # acrossfade=d=0 is treated by ffmpeg as UNSET and falls back to its
        # 1s default, eating (n-1) seconds of audio — a hard-cut reel must
        # concat instead (measured: 8-shot reel lost ~7s, foley drifted ahead)
        streams = "".join(f"[{i}:a]" for i in range(n))
        return f"{streams}concat=n={n}:v=0:a=1[aout]", "aout"
    filters = []
    prev_label = "[0:a]"
    for i in range(1, n):
        out_label = f"a{i}" if i < n - 1 else "aout"
        filters.append(
            f"{prev_label}[{i}:a]acrossfade=d={crossfade:.3f}[{out_label}]"
        )
        prev_label = f"[{out_label}]"
    return ";".join(filters), "aout"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--shots", required=True, help="Path to a shots.json.")
    args = ap.parse_args()

    cfg = load_config(args.shots)
    project_root = os.path.dirname(os.path.abspath(args.shots))
    media_dir = os.path.join(project_root, "media")
    final_dir = os.path.join(project_root, "final")
    os.makedirs(final_dir, exist_ok=True)

    w = cfg.get("width", DEFAULT_W)
    h = cfg.get("height", DEFAULT_H)
    fps = cfg.get("fps", DEFAULT_FPS)
    crossfade = cfg.get("crossfade", DEFAULT_CROSSFADE)
    shots = cfg["shots"]
    target_seconds = cfg.get("target_seconds", sum(s["seconds"] for s in shots))
    source_audio = cfg.get("source_audio")

    resolved = []
    for s in shots:
        path, kind = find_shot_media(media_dir, s["name"])
        if not path:
            sys.exit(f"ERROR: no media found for shot '{s['name']}' in {media_dir} "
                      f"(expected .png/.jpg or .mp4). Run generate_shots.py "
                      f"--shots {args.shots} first (or rename a _takeN file).")
        resolved.append((s, path, kind))

    # Pad every clip by one crossfade's worth so the xfade chain always has
    # enough overlap material; the final -t trim below corrects the total.
    pad = crossfade if len(resolved) > 1 else 0
    render_secs = [s["seconds"] + pad for s, _, _ in resolved]

    with tempfile.TemporaryDirectory(prefix="build_reel_") as tmp_dir:
        clip_paths, audio_paths = [], []
        for i, ((s, path, kind), secs) in enumerate(zip(resolved, render_secs)):
            print(f"Rendering {s['name']} ({kind}, {secs:.2f}s)...")
            if kind == "image":
                clip_paths.append(render_image_clip(path, secs, w, h, fps, tmp_dir, i))
            else:
                clip_paths.append(render_video_clip(path, secs, w, h, fps, tmp_dir, i))
            if not source_audio:
                audio_paths.append(render_clip_audio(path, kind, secs, tmp_dir, i))

        filter_complex, out_label, merged_dur = build_xfade_chain(
            len(clip_paths), render_secs, crossfade)

        video_only = os.path.join(tmp_dir, "video_only.mp4")
        ff_args = []
        for c in clip_paths:
            ff_args += ["-i", c]
        if filter_complex:
            ff_args += ["-filter_complex", filter_complex, "-map", f"[{out_label}]"]
        else:
            ff_args += ["-map", "0:v"]
        ff_args += ["-c:v", "libx264", "-pix_fmt", "yuv420p", "-r", str(fps), video_only]
        run(ff_args, "xfade chain")

        stamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        project_name = cfg.get("project", os.path.basename(project_root))
        final_path = os.path.join(final_dir, f"{project_name}_{stamp}.mp4")

        if source_audio:
            if not os.path.isfile(source_audio):
                sys.exit(f"ERROR: source_audio not found: {source_audio}")
            audio_dur = duration_of(source_audio)
            if audio_dur and audio_dur < target_seconds - 0.1:
                print(f"WARNING: source_audio is {audio_dur:.2f}s, shorter than "
                      f"target_seconds {target_seconds:.2f}s.")
            run(["-i", video_only, "-i", source_audio,
                 "-map", "0:v", "-map", "1:a:0",
                 "-t", f"{target_seconds:.3f}",
                 "-c:v", "copy", "-c:a", "aac", "-b:a", "192k",
                 final_path], "mux audio")
        else:
            a_filter, a_label = build_acrossfade_chain(len(audio_paths), crossfade)
            audio_only = os.path.join(tmp_dir, "audio_only.wav")
            af_args = []
            for a in audio_paths:
                af_args += ["-i", a]
            if a_filter:
                af_args += ["-filter_complex", a_filter, "-map", f"[{a_label}]"]
            else:
                af_args += ["-map", "0:a"]
            af_args += [audio_only]
            run(af_args, "acrossfade chain")

            run(["-i", video_only, "-i", audio_only,
                 "-map", "0:v", "-map", "1:a",
                 "-t", f"{target_seconds:.3f}",
                 "-c:v", "copy", "-c:a", "aac", "-b:a", "192k",
                 final_path], "mux own audio")

    print(f"\nDone -> {final_path}")


if __name__ == "__main__":
    main()
